version: "3.9"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - otelcol
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4318

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse

  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otelcol/otel-config.yaml:/etc/otelcol-config.yaml
    command: ["--config=/etc/otelcol-config.yaml"]
    ports:
      - "4318:4318" # HTTP OTLP
    depends_on:
      - clickhouse
    restart: always
